-- AlterTable
ALTER TABLE "Space" ADD COLUMN     "mapId" TEXT,
ALTER COLUMN "dimensions" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Space" ADD CONSTRAINT "Space_mapId_fkey" FOREIGN KEY ("mapId") REFERENCES "Map"("id") ON DELETE SET NULL ON UPDATE CASCADE;
